# Generated by Django 4.0.6 on 2022-07-28 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favicon',
            old_name='icon_Img',
            new_name='icon_Image',
        ),
        migrations.RemoveField(
            model_name='favicon',
            name='name',
        ),
    ]
